
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreateOrderService", targetNamespace = "http://create_order/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreateOrderService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client.Order
     */
    @WebMethod(operationName = "Create")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Create", targetNamespace = "http://create_order/", className = "client.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://create_order/", className = "client.CreateResponse")
    @Action(input = "http://create_order/CreateOrderService/CreateRequest", output = "http://create_order/CreateOrderService/CreateResponse")
    public Order create(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.Order
     */
    @WebMethod(operationName = "ReserveProducts")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReserveProducts", targetNamespace = "http://create_order/", className = "client.ReserveProducts")
    @ResponseWrapper(localName = "ReserveProductsResponse", targetNamespace = "http://create_order/", className = "client.ReserveProductsResponse")
    @Action(input = "http://create_order/CreateOrderService/ReserveProductsRequest", output = "http://create_order/CreateOrderService/ReserveProductsResponse")
    public Order reserveProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
